---

logger:
  hosts:
    192.168.3.205:
      ansible_user: vagrant
      ansible_password: vagrant
      ansible_port: 22
      ansible_connection: ssh
      ansible_ssh_common_args: '-o UserKnownHostsFile=/dev/null'

dc:
  hosts:
    x.x.x.x:

wef:
  hosts:
    y.y.y.y:

win10:
  hosts:
    z.z.z.z:

#exchange:
#  hosts:
#    w.w.w.w:
